/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import osu.salat23.circler.tables.ChatMembers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMembersRecord extends UpdatableRecordImpl<ChatMembersRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_members.id</code>.
     */
    public ChatMembersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.chat_members.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chat_members.client_id</code>.
     */
    public ChatMembersRecord setClientId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.chat_members.client_id</code>.
     */
    public String getClientId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.chat_members.chat_id</code>.
     */
    public ChatMembersRecord setChatId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.chat_members.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ChatMembers.CHAT_MEMBERS.ID;
    }

    @Override
    public Field<String> field2() {
        return ChatMembers.CHAT_MEMBERS.CLIENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return ChatMembers.CHAT_MEMBERS.CHAT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClientId();
    }

    @Override
    public Long component3() {
        return getChatId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClientId();
    }

    @Override
    public Long value3() {
        return getChatId();
    }

    @Override
    public ChatMembersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ChatMembersRecord value2(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public ChatMembersRecord value3(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public ChatMembersRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatMembersRecord
     */
    public ChatMembersRecord() {
        super(ChatMembers.CHAT_MEMBERS);
    }

    /**
     * Create a detached, initialised ChatMembersRecord
     */
    public ChatMembersRecord(Long id, String clientId, Long chatId) {
        super(ChatMembers.CHAT_MEMBERS);

        setId(id);
        setClientId(clientId);
        setChatId(chatId);
    }

    /**
     * Create a detached, initialised ChatMembersRecord
     */
    public ChatMembersRecord(osu.salat23.circler.tables.pojos.ChatMembers value) {
        super(ChatMembers.CHAT_MEMBERS);

        if (value != null) {
            setId(value.getId());
            setClientId(value.getClientId());
            setChatId(value.getChatId());
        }
    }
}
