/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import osu.salat23.circler.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public ChatsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chats.client_type</code>.
     */
    public ChatsRecord setClientType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.client_type</code>.
     */
    public String getClientType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.chats.client_id</code>.
     */
    public ChatsRecord setClientId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.client_id</code>.
     */
    public String getClientId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.chats.html_profile_template</code>.
     */
    public ChatsRecord setHtmlProfileTemplate(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.html_profile_template</code>.
     */
    public String getHtmlProfileTemplate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.chats.text_profile_template</code>.
     */
    public ChatsRecord setTextProfileTemplate(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.text_profile_template</code>.
     */
    public String getTextProfileTemplate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.chats.html_score_template</code>.
     */
    public ChatsRecord setHtmlScoreTemplate(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.html_score_template</code>.
     */
    public String getHtmlScoreTemplate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.chats.text_score_template</code>.
     */
    public ChatsRecord setTextScoreTemplate(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.text_score_template</code>.
     */
    public String getTextScoreTemplate() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Chats.CHATS.ID;
    }

    @Override
    public Field<String> field2() {
        return Chats.CHATS.CLIENT_TYPE;
    }

    @Override
    public Field<String> field3() {
        return Chats.CHATS.CLIENT_ID;
    }

    @Override
    public Field<String> field4() {
        return Chats.CHATS.HTML_PROFILE_TEMPLATE;
    }

    @Override
    public Field<String> field5() {
        return Chats.CHATS.TEXT_PROFILE_TEMPLATE;
    }

    @Override
    public Field<String> field6() {
        return Chats.CHATS.HTML_SCORE_TEMPLATE;
    }

    @Override
    public Field<String> field7() {
        return Chats.CHATS.TEXT_SCORE_TEMPLATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClientType();
    }

    @Override
    public String component3() {
        return getClientId();
    }

    @Override
    public String component4() {
        return getHtmlProfileTemplate();
    }

    @Override
    public String component5() {
        return getTextProfileTemplate();
    }

    @Override
    public String component6() {
        return getHtmlScoreTemplate();
    }

    @Override
    public String component7() {
        return getTextScoreTemplate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClientType();
    }

    @Override
    public String value3() {
        return getClientId();
    }

    @Override
    public String value4() {
        return getHtmlProfileTemplate();
    }

    @Override
    public String value5() {
        return getTextProfileTemplate();
    }

    @Override
    public String value6() {
        return getHtmlScoreTemplate();
    }

    @Override
    public String value7() {
        return getTextScoreTemplate();
    }

    @Override
    public ChatsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ChatsRecord value2(String value) {
        setClientType(value);
        return this;
    }

    @Override
    public ChatsRecord value3(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public ChatsRecord value4(String value) {
        setHtmlProfileTemplate(value);
        return this;
    }

    @Override
    public ChatsRecord value5(String value) {
        setTextProfileTemplate(value);
        return this;
    }

    @Override
    public ChatsRecord value6(String value) {
        setHtmlScoreTemplate(value);
        return this;
    }

    @Override
    public ChatsRecord value7(String value) {
        setTextScoreTemplate(value);
        return this;
    }

    @Override
    public ChatsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(Long id, String clientType, String clientId, String htmlProfileTemplate, String textProfileTemplate, String htmlScoreTemplate, String textScoreTemplate) {
        super(Chats.CHATS);

        setId(id);
        setClientType(clientType);
        setClientId(clientId);
        setHtmlProfileTemplate(htmlProfileTemplate);
        setTextProfileTemplate(textProfileTemplate);
        setHtmlScoreTemplate(htmlScoreTemplate);
        setTextScoreTemplate(textScoreTemplate);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(osu.salat23.circler.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setId(value.getId());
            setClientType(value.getClientType());
            setClientId(value.getClientId());
            setHtmlProfileTemplate(value.getHtmlProfileTemplate());
            setTextProfileTemplate(value.getTextProfileTemplate());
            setHtmlScoreTemplate(value.getHtmlScoreTemplate());
            setTextScoreTemplate(value.getTextScoreTemplate());
        }
    }
}
