version: '3.3'
services:

  application:
    build: .
    container_name: circler
    depends_on:
      - database
    environment:
      - OSU_CLIENT_ID=${OSU_CLIENT_ID}
      - OSU_CLIENT_SECRET=${OSU_CLIENT_SECRET}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - APPLICATION_ADMIN_USER=${APPLICATION_ADMIN_USER}
      - APPLICATION_ADMIN_PASSWORD=${APPLICATION_ADMIN_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "database:database"
    restart: on-failure
    volumes:
      - /home/salat23/circler/requiredcache:/root/.cache
    networks:
      - circler-app-network

  database:
    image: 'postgres:14.0-alpine'
    container_name: circler-database
    volumes:
      - /home/salat23/circler/database:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - circler-app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: circles-prometheus
    links:
      - "application:application"
    depends_on:
      - application
    ports:
      - "127.0.0.1:9090:9090"
    expose:
      - 9090
    volumes:
      - /home/salat23/circler/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: on-failure
    networks:
      - circler-app-network
    
  node-exporter:
    image: prom/node-exporter:latest
    container_name: circles-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - "127.0.0.1:9100:9100"
    networks:
      - circler-app-network

networks:
  circler-app-network:
    external: true
