version: '3.3'
services:

  application:
    build: .
    container_name: circler
    depends_on:
      - database
    links:
      - "database:database"
      - "prometheus:prometheus"
    restart: on-failure
    ports:
      - "8080:8080"

  database:
    image: 'postgres:14.0-alpine'
    container_name: circler-database
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: circles-prometheus
    depends_on:
      - application
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - /tmp/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: on-failure

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    container_name: circles-grafana
    ports:
      - '3000:3000'
    expose:
      - 3000
    links:
      - prometheus
    restart: on-failure
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  postgres_volume: {}
  grafana_storage:
    external: true