scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['application:8080']
        labels:
          application: 'Circler'
    basic_auth:
      username: ${APPLICATION_ADMIN_USER}
      password: ${APPLICATION_ADMIN_PASSWORD}
  - job_name: 'Server'
    scrape_interval: 2s
    static_configs:
      - targets: ["circles-node-exporter:9100"]