/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   id;
    private final String clientId;
    private final Long   chatId;

    public ChatMembers(ChatMembers value) {
        this.id = value.id;
        this.clientId = value.clientId;
        this.chatId = value.chatId;
    }

    public ChatMembers(
        Long   id,
        String clientId,
        Long   chatId
    ) {
        this.id = id;
        this.clientId = clientId;
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chat_members.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.chat_members.client_id</code>.
     */
    public String getClientId() {
        return this.clientId;
    }

    /**
     * Getter for <code>public.chat_members.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatMembers (");

        sb.append(id);
        sb.append(", ").append(clientId);
        sb.append(", ").append(chatId);

        sb.append(")");
        return sb.toString();
    }
}
