/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   id;
    private final String clientType;
    private final String clientId;
    private final String htmlProfileTemplate;
    private final String textProfileTemplate;
    private final String htmlScoreTemplate;
    private final String textScoreTemplate;

    public Chats(Chats value) {
        this.id = value.id;
        this.clientType = value.clientType;
        this.clientId = value.clientId;
        this.htmlProfileTemplate = value.htmlProfileTemplate;
        this.textProfileTemplate = value.textProfileTemplate;
        this.htmlScoreTemplate = value.htmlScoreTemplate;
        this.textScoreTemplate = value.textScoreTemplate;
    }

    public Chats(
        Long   id,
        String clientType,
        String clientId,
        String htmlProfileTemplate,
        String textProfileTemplate,
        String htmlScoreTemplate,
        String textScoreTemplate
    ) {
        this.id = id;
        this.clientType = clientType;
        this.clientId = clientId;
        this.htmlProfileTemplate = htmlProfileTemplate;
        this.textProfileTemplate = textProfileTemplate;
        this.htmlScoreTemplate = htmlScoreTemplate;
        this.textScoreTemplate = textScoreTemplate;
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.chats.client_type</code>.
     */
    public String getClientType() {
        return this.clientType;
    }

    /**
     * Getter for <code>public.chats.client_id</code>.
     */
    public String getClientId() {
        return this.clientId;
    }

    /**
     * Getter for <code>public.chats.html_profile_template</code>.
     */
    public String getHtmlProfileTemplate() {
        return this.htmlProfileTemplate;
    }

    /**
     * Getter for <code>public.chats.text_profile_template</code>.
     */
    public String getTextProfileTemplate() {
        return this.textProfileTemplate;
    }

    /**
     * Getter for <code>public.chats.html_score_template</code>.
     */
    public String getHtmlScoreTemplate() {
        return this.htmlScoreTemplate;
    }

    /**
     * Getter for <code>public.chats.text_score_template</code>.
     */
    public String getTextScoreTemplate() {
        return this.textScoreTemplate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(id);
        sb.append(", ").append(clientType);
        sb.append(", ").append(clientId);
        sb.append(", ").append(htmlProfileTemplate);
        sb.append(", ").append(textProfileTemplate);
        sb.append(", ").append(htmlScoreTemplate);
        sb.append(", ").append(textScoreTemplate);

        sb.append(")");
        return sb.toString();
    }
}
