/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMemberServerIdentifiers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   id;
    private final Long   chatMemberId;
    private final String playerIdentifier;
    private final String server;

    public ChatMemberServerIdentifiers(ChatMemberServerIdentifiers value) {
        this.id = value.id;
        this.chatMemberId = value.chatMemberId;
        this.playerIdentifier = value.playerIdentifier;
        this.server = value.server;
    }

    public ChatMemberServerIdentifiers(
        Long   id,
        Long   chatMemberId,
        String playerIdentifier,
        String server
    ) {
        this.id = id;
        this.chatMemberId = chatMemberId;
        this.playerIdentifier = playerIdentifier;
        this.server = server;
    }

    /**
     * Getter for <code>public.chat_member_server_identifiers.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for
     * <code>public.chat_member_server_identifiers.chat_member_id</code>.
     */
    public Long getChatMemberId() {
        return this.chatMemberId;
    }

    /**
     * Getter for
     * <code>public.chat_member_server_identifiers.player_identifier</code>.
     */
    public String getPlayerIdentifier() {
        return this.playerIdentifier;
    }

    /**
     * Getter for <code>public.chat_member_server_identifiers.server</code>.
     */
    public String getServer() {
        return this.server;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatMemberServerIdentifiers (");

        sb.append(id);
        sb.append(", ").append(chatMemberId);
        sb.append(", ").append(playerIdentifier);
        sb.append(", ").append(server);

        sb.append(")");
        return sb.toString();
    }
}
