/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import osu.salat23.circler.tables.ChatMemberServerIdentifiers;
import osu.salat23.circler.tables.ChatMembers;
import osu.salat23.circler.tables.Chats;
import osu.salat23.circler.tables.FlywaySchemaHistory;
import osu.salat23.circler.tables.records.ChatMemberServerIdentifiersRecord;
import osu.salat23.circler.tables.records.ChatMembersRecord;
import osu.salat23.circler.tables.records.ChatsRecord;
import osu.salat23.circler.tables.records.FlywaySchemaHistoryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatMemberServerIdentifiersRecord> CHAT_MEMBER_SERVER_IDENTIFIERS_CHAT_MEMBER_ID_SERVER_KEY = Internal.createUniqueKey(ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS, DSL.name("chat_member_server_identifiers_chat_member_id_server_key"), new TableField[] { ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS.CHAT_MEMBER_ID, ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS.SERVER }, true);
    public static final UniqueKey<ChatMemberServerIdentifiersRecord> CHAT_MEMBER_SERVER_IDENTIFIERS_PKEY = Internal.createUniqueKey(ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS, DSL.name("chat_member_server_identifiers_pkey"), new TableField[] { ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS.ID }, true);
    public static final UniqueKey<ChatMembersRecord> CHAT_MEMBERS_CLIENT_ID_CHAT_ID_KEY = Internal.createUniqueKey(ChatMembers.CHAT_MEMBERS, DSL.name("chat_members_client_id_chat_id_key"), new TableField[] { ChatMembers.CHAT_MEMBERS.CLIENT_ID, ChatMembers.CHAT_MEMBERS.CHAT_ID }, true);
    public static final UniqueKey<ChatMembersRecord> CHAT_MEMBERS_PKEY = Internal.createUniqueKey(ChatMembers.CHAT_MEMBERS, DSL.name("chat_members_pkey"), new TableField[] { ChatMembers.CHAT_MEMBERS.ID }, true);
    public static final UniqueKey<ChatsRecord> CHATS_CLIENT_TYPE_CLIENT_ID_KEY = Internal.createUniqueKey(Chats.CHATS, DSL.name("chats_client_type_client_id_key"), new TableField[] { Chats.CHATS.CLIENT_TYPE, Chats.CHATS.CLIENT_ID }, true);
    public static final UniqueKey<ChatsRecord> CHATS_PKEY = Internal.createUniqueKey(Chats.CHATS, DSL.name("chats_pkey"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatMemberServerIdentifiersRecord, ChatMembersRecord> CHAT_MEMBER_SERVER_IDENTIFIERS__CHAT_MEMBER_SERVER_IDENTIFIERS_CHAT_MEMBER_ID_FKEY = Internal.createForeignKey(ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS, DSL.name("chat_member_server_identifiers_chat_member_id_fkey"), new TableField[] { ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS.CHAT_MEMBER_ID }, Keys.CHAT_MEMBERS_PKEY, new TableField[] { ChatMembers.CHAT_MEMBERS.ID }, true);
    public static final ForeignKey<ChatMembersRecord, ChatsRecord> CHAT_MEMBERS__CHAT_MEMBERS_CHAT_ID_FKEY = Internal.createForeignKey(ChatMembers.CHAT_MEMBERS, DSL.name("chat_members_chat_id_fkey"), new TableField[] { ChatMembers.CHAT_MEMBERS.CHAT_ID }, Keys.CHATS_PKEY, new TableField[] { Chats.CHATS.ID }, true);
}
