/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import osu.salat23.circler.tables.ChatMemberServerIdentifiers;
import osu.salat23.circler.tables.ChatMembers;
import osu.salat23.circler.tables.Chats;
import osu.salat23.circler.tables.FlywaySchemaHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chat_member_server_identifiers</code>.
     */
    public final ChatMemberServerIdentifiers CHAT_MEMBER_SERVER_IDENTIFIERS = ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS;

    /**
     * The table <code>public.chat_members</code>.
     */
    public final ChatMembers CHAT_MEMBERS = ChatMembers.CHAT_MEMBERS;

    /**
     * The table <code>public.chats</code>.
     */
    public final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS,
            ChatMembers.CHAT_MEMBERS,
            Chats.CHATS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
