/*
 * This file is generated by jOOQ.
 */
package osu.salat23.circler;


import osu.salat23.circler.tables.ChatMemberServerIdentifiers;
import osu.salat23.circler.tables.ChatMembers;
import osu.salat23.circler.tables.Chats;
import osu.salat23.circler.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat_member_server_identifiers</code>.
     */
    public static final ChatMemberServerIdentifiers CHAT_MEMBER_SERVER_IDENTIFIERS = ChatMemberServerIdentifiers.CHAT_MEMBER_SERVER_IDENTIFIERS;

    /**
     * The table <code>public.chat_members</code>.
     */
    public static final ChatMembers CHAT_MEMBERS = ChatMembers.CHAT_MEMBERS;

    /**
     * The table <code>public.chats</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
